### ISSUE TITLE
MySQL output engine won't work within docker

### ISSUE THREAD

**Issue by fengberd** [cowrie/docker-cowrie#22]
Recently I've been moving cowrie into docker, with following docker run command:
```
docker run --name lol --rm \
        -p 2222:2222/tcp \
        -v "cowrie-etc:/cowrie/cowrie-git/etc" \
        cowrie/cowrie
```

The `cowrie-etc` volume contains the following mysql config:
```
[output_mysql]
enabled = true
host = 172.17.0.1
database = YAY
username = YAY
password = YAY
port = 3306
debug = false
```

However, cowrie throws the following exception on start:
```
Unhandled Error
Traceback (most recent call last):
File "/cowrie/cowrie-env/lib/python3.7/site-packages/twisted/application/app.py", line 678, in run
runApp(config)
File "/cowrie/cowrie-env/lib/python3.7/site-packages/twisted/scripts/twistd.py", line 30, in runApp
runner.run()
File "/cowrie/cowrie-env/lib/python3.7/site-packages/twisted/application/app.py", line 372, in run
self.application = self.createOrGetApplication()
File "/cowrie/cowrie-env/lib/python3.7/site-packages/twisted/application/app.py", line 434, in createOrGetApplication
ser = plg.makeService(self.config.subOptions)
--- <exception caught here> ---
File "/cowrie/cowrie-git/src/twisted/plugins/cowrie_plugin.py", line 148, in makeService
globals(), locals(), ['output']).Output()
File "/cowrie/cowrie-git/src/cowrie/output/mysql.py", line 6, in <module>
import MySQLdb
File "/cowrie/cowrie-env/lib/python3.7/site-packages/MySQLdb/__init__.py", line 24, in <module>
version_info, _mysql.version_info, _mysql.__file__
builtins.NameError: name '_mysql' is not defined
2021-03-25T12:38:35+0000 [-] Python Version 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
2021-03-25T12:38:35+0000 [-] Twisted Version 21.2.0
2021-03-25T12:38:35+0000 [-] Cowrie Version 2.2.0
2021-03-25T12:38:35+0000 [-] Unhandled Error
Traceback (most recent call last):
File "/cowrie/cowrie-env/lib/python3.7/site-packages/twisted/application/app.py", line 678, in run
runApp(config)
File "/cowrie/cowrie-env/lib/python3.7/site-packages/twisted/scripts/twistd.py", line 30, in runApp
runner.run()
File "/cowrie/cowrie-env/lib/python3.7/site-packages/twisted/application/app.py", line 372, in run
self.application = self.createOrGetApplication()
File "/cowrie/cowrie-env/lib/python3.7/site-packages/twisted/application/app.py", line 434, in createOrGetApplication
ser = plg.makeService(self.config.subOptions)
--- <exception caught here> ---
File "/cowrie/cowrie-git/src/twisted/plugins/cowrie_plugin.py", line 148, in makeService
globals(), locals(), ['output']).Output()
File "/cowrie/cowrie-git/src/cowrie/output/mysql.py", line 6, in <module>
import MySQLdb
File "/cowrie/cowrie-env/lib/python3.7/site-packages/MySQLdb/__init__.py", line 24, in <module>
version_info, _mysql.version_info, _mysql.__file__
builtins.NameError: name '_mysql' is not defined
2021-03-25T12:38:35+0000 [-] Failed to load output engine: mysql
```

---

After digging a bit deeper, I just found the `libmariadb.so.3` appears to be missing.
```
docker exec -it lol bash
. ~/cowrie-env/bin/activate
python -c "import MySQLdb"
```

Produces the following exception:
```
Traceback (most recent call last):
  File "/cowrie/cowrie-env/lib/python3.7/site-packages/MySQLdb/__init__.py", line 18, in <module>
    from . import _mysql
ImportError: libmariadb.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/cowrie/cowrie-env/lib/python3.7/site-packages/MySQLdb/__init__.py", line 24, in <module>
    version_info, _mysql.version_info, _mysql.__file__
NameError: name '_mysql' is not defined
```

I have no idea what's happening, since the Dockerfile already installed `default-libmysqlclient-dev` which should have install related libraries.
I've searched lib folders for this file, but with no luck. Any help is appreciated.

**Comment by micheloosterhof** [comment]
I think the Dockerfile doesn't install the MySQL libraries by default. `dpkg -l` should reveal that.

**Comment by fengberd** [comment]
Ah, I see. The Dockerfile just installed it in the builder, not the runtime.
Would you mind to add this library to runtime? After adding it to the runtime, I didn't noticed significant image size increase (442MB -> 481MB).
Or, if there're some other considerations, createing a separate `:mysql` tag might be a good idea?

**Comment by micheloosterhof** [comment]
Ah! Of course we can add it to the runtime, I think I it was accidentally
removed when we split between builder and runtime.

**Comment by fengberd** [comment]
Solved in https://github.com/cowrie/docker-cowrie/commit/aa65a14bd2fe41a428dad0eb9aa8ff3940cb5253, thanks.
