### ISSUE TITLE
SQL logging error

### ISSUE THREAD

**Issue by michaelmsimpson** [cowrie/docker-cowrie#24]
Hello! I am having an issue with getting docker-cowrie to tie in with another mysql container. You can see my full configuration [here](https://github.com/michaelmsimpson/cowrie-kippo-graph). The issue comes when (I presume) cowrie is trying to write to the sql database. I'm not sure if this is an issue with my specific docker configuration, or with docker-cowrie itself.

Here is the error that is happening:

```2021-05-03T20:43:52+0000 [twisted.internet.defer#critical] Unhandled error in Deferred:
2021-05-03T20:43:52+0000 [twisted.internet.defer#critical]
Traceback (most recent call last):
File "/cowrie/cowrie-env/lib/python3.7/site-packages/twisted/internet/base.py", line 1292, in mainLoop
self.runUntilCurrent()
File "/cowrie/cowrie-env/lib/python3.7/site-packages/twisted/internet/base.py", line 886, in runUntilCurrent
f(*a, **kw)
File "/cowrie/cowrie-env/lib/python3.7/site-packages/twisted/internet/defer.py", line 501, in errback
self._startRunCallbacks(fail)
File "/cowrie/cowrie-env/lib/python3.7/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
self._runCallbacks()
--- <exception caught here> ---
File "/cowrie/cowrie-env/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
current.result = callback(current.result, *args, **kw)
File "/cowrie/cowrie-git/src/cowrie/output/mysql.py", line 80, in sqlerror
if error.value[0] in (1146, 1406):
builtins.TypeError: 'OperationalError' object is not subscriptable```

**Comment by micheloosterhof** [comment]
Thanks for reporting this! This is actually not an issue with the Docker version, but inside the MySQL output plugin.

**Comment by micheloosterhof** [comment]
I think the code here should be not 
```
    def sqlerror(self, error):
        """
        1146, "Table '...' doesn't exist"
        1406, "Data too long for column '...' at row ..."
        """
        if error.value[0] in (1146, 1406):
            log.msg(f"output_mysql: MySQL Error: {error.value}")
            log.msg("MySQL schema maybe misconfigured, doublecheck database!")
        else:
            log.err(f"output_mysql: MySQL Error: {error.value}")
```
but
```
    def sqlerror(self, error):
        """
        1146, "Table '...' doesn't exist"
        1406, "Data too long for column '...' at row ..."
        """
        if error[0] in (1146, 1406):
            log.msg(f"output_mysql: MySQL Error: {error!r}")
            log.msg("MySQL schema maybe misconfigured, doublecheck database!")
        else:
            log.err(f"output_mysql: MySQL Error: {error!r}")
```

Do you have the opportunity to test this? I don't have a MySQL environment set up right now,

**Comment by micheloosterhof** [comment]
I've made some changes and that'll be part of a larger commit i'll add soon. Give it a few days and I should add that and rebuilt the Docker image.

**Comment by micheloosterhof** [comment]
Image was rebuilt. take a look.

**Comment by michaelmsimpson** [comment]
I am still getting the same error, unfortunately. I tried completely removing my image from docker and rebuilding but no luck. Thank you for the help, regardless!

**Comment by micheloosterhof** [comment]
Your error message should have changed at least? Could you paste the new error message, please?

**Comment by michaelmsimpson** [comment]
I get that same error, but in addition to it, I also get the following:

```
--- <exception caught here> ---
File "/cowrie/cowrie-env/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
result = result.throwExceptionIntoGenerator(g)
File "/cowrie/cowrie-env/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
return g.throw(self.type, self.value, self.tb)
File "/cowrie/cowrie-git/src/cowrie/output/mysql.py", line 168, in write
(entry['version'],))
File "/cowrie/cowrie-env/lib/python3.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
result = inContext.theWork()
File "/cowrie/cowrie-env/lib/python3.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
File "/cowrie/cowrie-env/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
return self.currentContext().callWithContext(ctx, func, *args, **kw)
File "/cowrie/cowrie-env/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
return func(*args,**kw)
File "/cowrie/cowrie-git/src/cowrie/output/mysql.py", line 36, in _runInteraction
raise e
File "/cowrie/cowrie-git/src/cowrie/output/mysql.py", line 33, in _runInteraction
self, interaction, *args, **kw)
File "/cowrie/cowrie-env/lib/python3.7/site-packages/twisted/enterprise/adbapi.py", line 460, in _runInteraction
conn = self.connectionFactory(self)
File "/cowrie/cowrie-env/lib/python3.7/site-packages/twisted/enterprise/adbapi.py", line 36, in __init__
self.reconnect()
File "/cowrie/cowrie-env/lib/python3.7/site-packages/twisted/enterprise/adbapi.py", line 76, in reconnect
self._connection = self._pool.connect()
File "/cowrie/cowrie-env/lib/python3.7/site-packages/twisted/enterprise/adbapi.py", line 427, in connect
conn = self.dbapi.connect(*self.connargs, **self.connkw)
File "/cowrie/cowrie-env/lib/python3.7/site-packages/MySQLdb/__init__.py", line 130, in Connect
return Connection(*args, **kwargs)
File "/cowrie/cowrie-env/lib/python3.7/site-packages/MySQLdb/connections.py", line 185, in __init__
super().__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
```

I feel like this last line is the most important.

**Comment by micheloosterhof** [comment]
You’re right! Something is misconfigured and it can’t reach the MySQL
server. Can you share your configuration?

**Comment by michaelmsimpson** [comment]
I'm configuring my cowrie environment using my docker-compose file [here](https://raw.githubusercontent.com/michaelmsimpson/cowrie-kippo-graph/master/docker-compose.yml). My  full configuration is linked above, if you want to check specific Dockerfiles for my database or cowrie. Thanks so much!

**Comment by micheloosterhof** [comment]
Your hostname will not be `localhost` because your database runs in another container.

**Comment by michaelmsimpson** [comment]
Thank you!
