### ISSUE TITLE
 Failed to load output engine: hpfeeds

### ISSUE THREAD

**Issue by hallmanhe** [cowrie/docker-cowrie#3]
```
2018-11-19T06:55:53+0000 [-] Python Version 3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516]
2018-11-19T06:55:53+0000 [-] Twisted Version 18.9.0
2018-11-19T06:55:53+0000 [-] Loaded output engine: jsonlog
2018-11-19T06:55:53+0000 [-] Early version of hpfeeds-output, untested!
2018-11-19T06:55:53+0000 [-] hpfeeds client init broker 106.75.178.69:10000, identifier bdc2c520-ea3d-11e8-bed7-52540059f14b
2018-11-19T06:55:53+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/cowrie/cowrie-env/lib/python3.5/site-packages/twisted/application/app.py", line 674, in run
	    runApp(config)
	  File "/cowrie/cowrie-env/lib/python3.5/site-packages/twisted/scripts/twistd.py", line 25, in runApp
	    runner.run()
	  File "/cowrie/cowrie-env/lib/python3.5/site-packages/twisted/application/app.py", line 381, in run
	    self.application = self.createOrGetApplication()
	  File "/cowrie/cowrie-env/lib/python3.5/site-packages/twisted/application/app.py", line 448, in createOrGetApplication
	    ser = plg.makeService(self.config.subOptions)
	--- <exception caught here> ---
	  File "/cowrie/cowrie-git/src/twisted/plugins/cowrie_plugin.py", line 127, in makeService
	    globals(), locals(), ['output']).Output()
	  File "/cowrie/cowrie-git/src/cowrie/output/hpfeeds.py", line 258, in __init__
	    cowrie.core.output.Output.__init__(self)
	  File "/cowrie/cowrie-git/src/cowrie/core/output.py", line 97, in __init__
	    self.start()
	  File "/cowrie/cowrie-git/src/cowrie/output/hpfeeds.py", line 267, in start
	    self.client = hpclient(server, port, ident, secret, debug)
	  File "/cowrie/cowrie-git/src/cowrie/output/hpfeeds.py", line 129, in __init__
	    self.connect()
	  File "/cowrie/cowrie-git/src/cowrie/output/hpfeeds.py", line 143, in connect
	    self.handle_established()
	  File "/cowrie/cowrie-git/src/cowrie/output/hpfeeds.py", line 161, in handle_established
	    self.read()
	  File "/cowrie/cowrie-git/src/cowrie/output/hpfeeds.py", line 184, in read
	    for opcode, data in self.unpacker:
	builtins.TypeError: iter() returned non-iterator of type 'FeedUnpack'
	
2018-11-19T06:55:53+0000 [-] Failed to load output engine: hpfeeds
2018-11-19T06:55:53+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 18.9.0 (/cowrie/cowrie-env/bin/python3 3.5.3) starting up.
2018-11-19T06:55:53+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
2018-11-19T06:55:53+0000 [-] CowrieSSHFactory starting on 2222
2018-11-19T06:55:53+0000 [cowrie.ssh.factory.CowrieSSHFactory#info] Starting factory <cowrie.ssh.factory.CowrieSSHFactory object at 0x7f9846ca7860>
2018-11-19T06:55:53+0000 [-] Ready to accept SSH connections
```

**Comment by micheloosterhof** [comment]
Can you try with hpfeeds3, please?

**Comment by hallmanhe** [comment]
^_^thank you very much. It can work now after i try hpfeeds3

**Comment by willraharja** [comment]
Hello there, I would like to ask how do you use hpfeeds3.py? It seems to me that cowrie default configuration always use hpfeeds.py and I don't know how to set it to hpfeeds3.py. 

Thanks in advance

**Comment by micheloosterhof** [comment]
It’s the same has hpfeeds, just add a 3

**Comment by willraharja** [comment]
I found a section in cowrie.cfg.dist that is written as [output_hpfeeds] there, do I change it as [output_hpfeeds3] or should I configure it with another file (making it into separate file named cowrie.cfg and [output.hpfeeds3]

**Comment by micheloosterhof** [comment]
Correct!

**Comment by willraharja** [comment]
okay then, thank you for the help. I'm gonna try it and gonna tell you whether it works or not. cheers!
